### ISSUE TITLE
Support setting an action try timeout

### ISSUE THREAD

**Issue by atoulme** [Wandalen/wretry.action#109]
Sometimes the action being retried doesn't fail but eats up time and eventually times out. In some cases, we have seen actions run for 60 minutes while hung up on a network connection.

It would be great if your retry action would support a way to set the `timeout-minutes` setting available today at the step level.

**Comment by dmvict** [comment]
Hello @atoulme  

Thank you for your report. 

I think it is good to have such option in the action. I will implement it when I have time.

**Comment by samiura** [comment]
+1

**Comment by dmvict** [comment]
Hello @atoulme @samiura 

The feature was introduced a time ago and I forgot to notify you. 
Please, check the new feature and provide some feedback.
