### ISSUE TITLE
Error: Expects object-like or long-like {-butMap-}

### ISSUE THREAD

**Issue by AdamAtFloreo** [Wandalen/wretry.action#124]
The following use of the action keeps failing in my project with "Error: Expects object-like or long-like {-butMap-}"
I have no idea what's wrong with it.

      - uses: Wandalen/wretry.action@v1.3.0
        with:
          action: RageAgainstThePixel/setup-ovr-platform-util@v1
          attempt_limit: 5
          attempt_delay: 15000

**Comment by dmvict** [comment]
Hello @AdamAtFloreo 

I'll look at this when I have time.

**Comment by dmvict** [comment]
Hello @AdamAtFloreo 

You can try new version `v2.1.0`. It should solve your issue.
