### ISSUE TITLE
Getting Node.js 16 deprecation warnings when using this action

### ISSUE THREAD

**Issue by ClementTsang** [Wandalen/wretry.action#126]
Been seeing the following warning when running workflows that use this action:

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: Wandalen/wretry.action@v1.3.0_js_action. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

I'm guessing a dependency bump + release is needed? Thanks!

**Comment by dmvict** [comment]
Hello @ClementTsang 

Thank you for the issue. We'll release it soon.

**Comment by dmvict** [comment]
Hello @ClementTsang 

What is the version of action in the workflow? The latest `v1.3.0` uses nodejs 20 https://github.com/Wandalen/wretry.action/blob/js_action/action.yml#L55.

**Comment by ClementTsang** [comment]
Ah, I found the confusion - in https://github.com/ClementTsang/bottom/actions/runs/7689540721, I was using `Wandalen/wretry.action@a163f62ae554a8f3cbe27b23db15b60c0ae2e93c` since that's what I saw was the hash in https://github.com/Wandalen/wretry.action/releases/tag/v1.3.0. That points to [here](https://github.com/Wandalen/wretry.action/tree/a163f62ae554a8f3cbe27b23db15b60c0ae2e93c/), which matches what's currently in the `master` branch, but what's linked above that has the updated node version is the `js_action` branch.

**Comment by DL6ER** [comment]
If using

``` yaml
uses: Wandalen/wretry.action@v1.3.0
```

here

https://github.com/pi-hole/FTL/blob/ce4407b53696b3fd1d5b76a4af7e7dfd1bd647eb/.github/workflows/build.yml#L90

isn't right, what are we supposed to use instead?

![Screenshot from 2024-01-29 16-18-54](https://github.com/Wandalen/wretry.action/assets/16748619/26412d50-3479-4f77-8444-5eca40ae7155)

**Comment by dpanici** [comment]
^ [having the same issue](https://github.com/PlasmaControl/DESC/actions/runs/7706602813?pr=843)

Really appreciate the dev work done on this action and any help in getting this fixed!

**Comment by TokisanGames** [comment]
The *only* branch or tag with the node20 commit ba4878c3bf6fcdb73638487d901f06e2f24a7117 is `js_action`.

However this doesn't work 
```
        uses: Wandalen/wretry.action@js_action
```

Because the script is broken

```
Wandalen/wretry.action/js_action/action.yml (Line: 39, Col: 18): Unrecognized named-value: 'inputs'. Located at position 9 within expression: toJSON( inputs )
Fail to load Wandalen/wretry.action/js_action/action.yml
```

The only option is to wait for a fix and release.
