### ISSUE TITLE
Doesn't work with private github repo actions

### ISSUE THREAD

**Issue by mycarrysun** [Wandalen/wretry.action#136]
When trying to use a private github repo for the action parameter, it does not work (we use this action daily in our workflow and it does work, just not when passed in here). I'm guessing a token/secret is not being used. I imagine this is a security feature so that actions can't see what's in your private repo so not sure if its even possible but would be great if we could get this working.

Here is the output:

<img width="868" alt="Screen Shot 2024-03-06 at 11 11 43 AM" src="https://github.com/Wandalen/wretry.action/assets/9121901/34f7b04a-f9e6-4d3d-b7ec-f3c30cfe9655">

**Comment by dmvict** [comment]
Hello @mycarrysun  

I've released new version `v2.1.0`. The action has option `github_token` and it is the option for downloading private actions. Please, try new version and give me a feedback. 
Please, be care about the token, it should have correct access rights.
