### ISSUE TITLE
unable to retry action pytooling/releaser

### ISSUE THREAD

**Issue by kikmon** [Wandalen/wretry.action#52]
Hi

I'm trying to use wretry to retry the releaser action from pytooling, and wtrey is failing, because it tries to clone a non-existing repo
`      - name: publish package
        uses: Wandalen/wretry.action@v1.0.11
        with:
          action: pyTooling/Actions/releaser@r0
          with: |
            token: ${{ secrets.GITHUB_TOKEN }}
            tag: ${{ github.ref_name }}
            rm: true # do not keep old latest artifacts
            files: |
              *.zip
          attempt_limit: 3
          attempt_delay: 3000
`
Is there a specific syntax to use to make this use case work ?

Here's a link to the whole yaml file
https://github.com/kikmon/huc/blob/retry/.github/workflows/build.yml

and here's the log output
https://github.com/kikmon/huc/runs/6849866601?check_suite_focus=true

**Comment by dmvict** [comment]
Hi, @kikmon 

Thank you for your report. 
You're right, some features not implemented yet. For your issue it is : 
- advanced paths syntax for actions ( this [link](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-public-action-in-a-subdirectory) and next ) 
- retry Docker actions ( now action correctly retries JS actions and commands ) 

I'll try to resolve issue as soon as I can.

**Comment by kikmon** [comment]
Thanks
Github infra being unstable, it's gonna be really useful to have these issues.

**Comment by khanhere** [comment]
I am also seeing the same issue 😞

**Comment by dmvict** [comment]
Hello, @kikmon and @khanhere 

The feature will be available when the PR https://github.com/Wandalen/wretry.action/pull/99 will be merged and published.

**Comment by dmvict** [comment]
Hello, @kikmon  and @khanhere 

The new version is released. Please, try version `v1.2.0` and give me a feedback.
