### ISSUE TITLE
Upgrade action to use nodejs 16

### ISSUE THREAD

**Issue by tino-fernandez** [Wandalen/wretry.action#74]
hello, thank you for this useful action.

i am getting some warnings about the nodejs version used.

`
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: Wandalen/wretry.action, Wandalen/wretry.action
`

**Comment by dmvict** [comment]
Hello, @tino-fernandez 

The new version of the action uses the node v16. 
The PR #73 was merged and published. 
https://github.com/Wandalen/wretry.action/pull/73/files

**Comment by tino-fernandez** [comment]
thank you a lot

**Comment by dmvict** [comment]
@tino-fernandez 

Did your question solved? Can you close the issue?

**Comment by tino-fernandez** [comment]
yes thanks
