### ISSUE TITLE
Issue: not able to work with codecov-action

### ISSUE THREAD

**Issue by williamfgc** [Wandalen/wretry.action#75]
Looking mostly for guidance. We are trying to use `wretry.action` with [codecov-action](https://github.com/codecov/codecov-action) and things don't work as expected. Am I missing something or this is not supported at all? Here is the [PR action logs](https://github.com/QMCPACK/qmcpack/actions/runs/3586046379/jobs/6036204370#step:9:1) and the [PR](https://github.com/QMCPACK/qmcpack/pull/4347). Any insight would be appreciated.

**Comment by dmvict** [comment]
Hello, @williamfgc  

I have a lot of work and cannot fix it quickly. Sorry for that. I will fix it later.

**Comment by dmvict** [comment]
Hello, @williamfgc  

I found a few hours to work with the issue. 
I wrote the test with similar inputs and action found the files of the actions. 
https://github.com/Wandalen/wretry.action/pull/76/files 

Later, I will write another experimental workflow to check the action. 

Please, give me an answer. 

Could the previous steps in your workflow delete files of the action with the paths in https://github.com/QMCPACK/qmcpack/actions/runs/3586046379/jobs/6036204370#step:9:679?
