### ISSUE TITLE
Support `Wandalen/wretry.action@v1`

### ISSUE THREAD

**Issue by Hongbo-Miao** [Wandalen/wretry.action#78]
Currently,

- `Wandalen/wretry.action@v1.0.36`
- `wandalen/wretry.action@v1.0.36`

can succeed.

However,

- `Wandalen/wretry.action@v1`
- `wandalen/wretry.action@v1`

failed with error:

> Unable to resolve action `Wandalen/wretry.action@v1`, unable to find version `v1`

It would be great to support `@v1` which is more common. Thanks! 😃

**Comment by dmvict** [comment]
Hello, @Hongbo-Miao 

The release `v1` is in repository.
