### ISSUE TITLE
What's the purpose of master branch ?

### ISSUE THREAD

**Issue by yukha-dw** [Wandalen/wretry.action#82]
Hello, I wonder what's the purpose [master branch](https://github.com/Wandalen/wretry.action) while all of the logic is on [js_action branch](https://github.com/Wandalen/wretry.action/tree/js_action)? Thank you

**Comment by dmvict** [comment]
Hello, @yukha-dw 

The purpose of the `master` branch is in wrapping the action in `js_action` branch. It allows us to use workflow contexts of the main action in the called action from `js_action`.  It's a way to share workflow contexts.

**Comment by yukha-dw** [comment]
Hello @dmvict, it's such an interesting format and caught me off-guard when running the action.
Thank you for your answer!
