### ISSUE TITLE
Wrong interpretation of null when setting up action options

### ISSUE THREAD

**Issue by dfdez** [Wandalen/wretry.action#85]
When taking a look to this issue https://github.com/actions/checkout/issues/1378 we have found that the problem was rewarding this action.

Just to give a brief context @bzbarsky-apple was reporting tha `sparse-checkout` was running when it didn't add any option related to `sparse-checkout`. And after some digging I figure out that the problem might be related with this line of code.

https://github.com/Wandalen/wretry.action/blob/b9c799d9c0a3dda3df30144ca148296e6b896996/src/Common.js#L134

In the `actions/checkout` we set `sparse-checkout` to `null` but it seems that this `default` value when evaluated on this action is turning the default value `null` to `"null"`.

The reason for this is because `wretry.action` evaluates all the inputs. In the process of creating the default input `INPUT_SPARSE_CHECKOUT` the env is set to `null` and when reading from the `process.env` instead of being a `null` value is  a literal string `"null"`

https://github.com/Wandalen/wretry.action/blob/b9c799d9c0a3dda3df30144ca148296e6b896996/src/Common.js#L200

That is why in this [job](https://github.com/project-chip/connectedhomeip/actions/runs/5223466703/jobs/9430364364) without setting up `sparse-checkout` `wretry.action` is setting up the env `INPUT_SPARSE_CHECKOUT=null` creating indirectly a default value of `sparse-checkout: "null"` on the `actions/checkout` options

**Comment by dmvict** [comment]
Hello, @dfdez 

Here is PR https://github.com/Wandalen/wretry.action/pull/100 with the fix. 

I will notify you when it will be published.

**Comment by dmvict** [comment]
Hello, @dfdez 

The new version is released. Please try `v1.2.0` and close the issue if it solves the problem.

**Comment by dfdez** [comment]
Before `v1.2.0`: 

![image](https://github.com/Wandalen/wretry.action/assets/59401547/f6320e83-b742-410c-a692-bb9b3792d6b3)

With `v1.2.0`:

![image](https://github.com/Wandalen/wretry.action/assets/59401547/242693c6-b2d7-4401-b477-0ea6660b87fc)

Working perfect! Nice job! 🥳
