### ISSUE TITLE
Failed to run with v1.0.37

### ISSUE THREAD

**Issue by LucasXu0** [Wandalen/wretry.action#89]
Hi. It seems the uuid is missing in the latest version.

```
Run Wandalen/wretry.action@master
Run Wandalen/wretry.action@v1.0.37_js_action
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'uuid'
```

Error link:
https://github.com/AppFlowy-IO/AppFlowy/actions/runs/5287644855/jobs/9572470487?pr=2823

**Comment by dmvict** [comment]
Hello, @LucasXu0 

The version `1.0.41` is not published yet but it works. 
Close the issue, please.
